image: Visual Studio 2015

install:
  - choco install gitversion.portable -pre -y

assembly_info:
  patch: false

cache:
  - '%USERPROFILE%\.nuget\packages' -> packet.lock 
  - '%LocalAppData%\NuGet\Cache' -> packet.lock
  - '%LocalAppData%\NuGet\v3-cache' -> paket.lock
  - paket-files -> packet.lock

before_build:
  - ps: gitversion /l console /output buildserver /updateAssemblyInfo

build_script:
  - cmd: .\build.cmd Publish

test: off

on_finish:
- ps: $blockRdp = $false; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
